# To run: conda env create -f environment.yml
name: polygen_tf_env
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - networkx=2.6.3
    - pip:
        - tensorflow==2.11
        - tensorflow-probability==0.19.0