# To run: conda env create -f environment.yml
name: polygen_tf_env
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pyyaml=5.4.1 # tf-models-official will try to install pyyaml=5.4.1 through pypi, which results in an error. So we install it manually through conda
    - matplotlib=3.7.1
    - networkx=2.6.3
    - pip
    - pip:
        - tensorflow==2.11.1
        - tensorflow-probability==0.19.0
        - tf-models-official==2.11.6